---


- name: Install a list of MariaDB packages 
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - mariadb-server
    - mariadb-client
    - mariadb-common
    - python-mysqldb
  tags: mariadb

- name: enable MariaDB service
  systemd:
    name: mariadb
    enabled: yes
  tags: mariadb


- name: Make sure MariaDb service is running
  systemd:
    state: started
    name: mariadb
  tags: mariadb

- name: adding firewalld rules for MariaDB
  firewalld:
    service: mysql
    permanent: true
    state: enabled
  notify: Reloading firewalld rules
  tags: mariadb



- name: Add my.cnf
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=root group=root mode=0600
  tags: mariadb

- name: Restart MariaDb
  systemd: 
    state: restarted
    name: mariadb
  tags: mariadb


# Set root password
# UPDATE mysql.user SET Password=PASSWORD('mysecret') WHERE User='root';
# FLUSH PRIVILEGES;

- name: Set root Password
  mysql_user: login_password={{ mysql_root_password }} check_implicit_admin=yes name=root host={{ item }} password={{ mysql_root_password }} state=present 
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
  tags: mariadb

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
  tags: mariadb

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False
  tags: mariadb

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False
  tags: mariadb

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  tags: mariadb

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
  tags: mariadb



